CreateConVar("sbtm_name_red", "Red Team", FCVAR_ARCHIVE + FCVAR_REPLICATED, "Team name for the first team.")
CreateConVar("sbtm_name_blue", "Blue Team", FCVAR_ARCHIVE + FCVAR_REPLICATED, "Team name for the second team.")
CreateConVar("sbtm_name_green", "Green Team", FCVAR_ARCHIVE + FCVAR_REPLICATED, "Team name for the third team.")
CreateConVar("sbtm_name_yellow", "Yellow Team", FCVAR_ARCHIVE + FCVAR_REPLICATED, "Team name for the fourth team.")

local function colorconvar(t, default)
    CreateConVar("sbtm_clr_" .. t .. "_" .. "r", default.r, FCVAR_ARCHIVE + FCVAR_REPLICATED, "", 0, 255)
    CreateConVar("sbtm_clr_" .. t .. "_" .. "g", default.g, FCVAR_ARCHIVE + FCVAR_REPLICATED, "", 0, 255)
    CreateConVar("sbtm_clr_" .. t .. "_" .. "b", default.b, FCVAR_ARCHIVE + FCVAR_REPLICATED, "", 0, 255)
end
colorconvar("red", Color(255, 0, 0))
colorconvar("blue", Color(0, 0, 255))
colorconvar("green", Color(0, 255, 0))
colorconvar("yellow", Color(255, 255, 0))

hook.Add("CreateTeams", "SBTM", function()
    team.SetUp(SBTM_RED, GetConVar("sbtm_name_red"):GetString()     or "Red Team",      SBTM:ConVarTeamColor(SBTM_RED), false)
    team.SetUp(SBTM_BLU, GetConVar("sbtm_name_blue"):GetString()    or "Blue Team",     SBTM:ConVarTeamColor(SBTM_BLU), false)
    team.SetUp(SBTM_GRN, GetConVar("sbtm_name_green"):GetString()   or "Green Team",    SBTM:ConVarTeamColor(SBTM_GRN), false)
    team.SetUp(SBTM_YEL, GetConVar("sbtm_name_yellow"):GetString()  or "Yellow Team",   SBTM:ConVarTeamColor(SBTM_YEL), false)
end)